### ISSUE TITLE
Crash While Initialize

### ISSUE THREAD

**Issue by ruchitshah21** [dev-juyoung/CroPicker#3]
`07-11 14:39:05.606 13179-13179/com.jos E/AndroidRuntime: FATAL EXCEPTION: main
                                                         Process: com.jos, PID: 13179
                                                         Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jos/xyz.dev_juyoung.cropicker.activities.DirectoryActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void xyz.dev_juyoung.cropicker.base.CroPickerApplication.progressShow(android.app.Activity)' on a null object reference
                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                             at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                             at android.os.Looper.loop(Looper.java:148)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                          Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void xyz.dev_juyoung.cropicker.base.CroPickerApplication.progressShow(android.app.Activity)' on a null object reference
                                                             at xyz.dev_juyoung.cropicker.base.CroPickerActivity.progressShow(CroPickerActivity.java:142)
                                                             at xyz.dev_juyoung.cropicker.activities.DirectoryActivity.onCreate(DirectoryActivity.java:39)
                                                             at android.app.Activity.performCreate(Activity.java:6251)
                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                             at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                             at android.os.Looper.loop(Looper.java:148) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

**Comment by dev-juyoung** [comment]
Probably because of the error caused by the application class created to use the Progress Dialog in common.

To solve this problem, I moved the problem-causing code to the Activity stage, removed the Application Class of my library, and updated the modified version.

Sorry for the inconvenience.
Please update to version 1.0.3!

**Please check and leave a comment if the problem is resolved. After waiting for your answer, I will close the issue.**
