### ISSUE TITLE
Crash when click button on mainactivitiy

### ISSUE THREAD

**Issue by gpt3ch** [dev-juyoung/CroPicker#4]
`08-05 23:29:15.936 2804-2804/xyz.dev_juyoung.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: xyz.dev_juyoung.sample, PID: 2804
                                                                      java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/xyz.dev_juyoung.sample-1/base.apk)
                                                                          at xyz.dev_juyoung.cropicker.adapters.DirectoryAdapter.onBindView(DirectoryAdapter.java:53)
                                                                          at xyz.dev_juyoung.cropicker.adapters.DirectoryAdapter.onBindView(DirectoryAdapter.java:24)
                                                                          at xyz.dev_juyoung.cropicker.base.CroPickerRecyclerAdapter.onBindViewHolder(CroPickerRecyclerAdapter.java:49)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                          at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                          at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                          at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                          at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                          at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
                                                                          at android.view.View.measure(View.java:19759)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                          at android.view.View.measure(View.java:19759)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                          at android.view.View.measure(View.java:19759)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                          at android.view.View.measure(View.java:19759)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at android.view.View.measure(View.java:19759)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                          at android.view.View.measure(View.java:19759)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
                                                                          at android.view.View.measure(View.java:19759)
                                                                          at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2283)
                                                                          at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1370)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6348)
08-05 23:29:15.937 2804-2804/xyz.dev_juyoung.sample E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
`

**Comment by dev-juyoung** [comment]
Are you using Glide 4.x in your App Module?
The problem seems to be seen by users using the glide 4.x version.
